server:
  port: 8091

spring:
  application:
    name: zuul-proxy

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    preferIpAddress: true

zuul:
  routes:
    customer-service:
      serviceId: customer-service
  host:
    socket-timeout-millis: 30000

logging:
  level:
    ROOT: INFO
    org.springframework: ERROR
    com.example: TRACE
  pattern:
    console: "%-5level %d{yyyy-MM-dd HH:mm:ss} - %msg%n"


